# Generated by Django 5.0.6 on 2024-07-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="myapp.company",
            ),
        ),
    ]
