# Generated by Django 5.0.6 on 2024-07-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_supplier_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyName",
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplierName",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
