# Generated by Django 5.0.6 on 2024-07-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_user_supplier_alter_company_companyname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="myapp.supplier",
            ),
        ),
    ]
